### ISSUE TITLE
Syntax for rgba() color

### ISSUE THREAD

**Issue by thierryk** [yahoo/atomizer#100]
I think we could go this route:

```css
.C-FFF\.4 {
    color: rgba(255, 255, 255, .4); 
}
```

Same as we have now, `C-` followed by `hex` value to what we'd add the transparency value.
The `.` in there can be used as marker since `1` (opaque) should be expressed as plain `grb()`/`hex` value.
Thoughts?
