### ISSUE TITLE
LineClamp output is incorrect

### ISSUE THREAD

**Issue by src-code** [yahoo/atomizer#143]
It's been noted that when you have multiple instances of a helper like `LineClamp`, you may get incorrect CSS output such as:

```css
.LineClamp\(2\,32px\),.LineClamp\(2\,39px\),.LineClamp\(3\,50\.7px\) {
    -webkit-line-clamp: 2;
    max-height: 32px
}
```
I suspect this is somehow related to the logic used to combine selectors, possibly due to use of parens, but that's just a hunch.  Will need to look more deeply into this.

@renatoi @thierryk @karenrfay @kfay
