### ISSUE TITLE
Unexpected CSS token: $

### ISSUE THREAD

**Issue by 3den** [yahoo/atomizer#185]
I am getting this `Unexpected CSS token: $` several times, seems like atomizer is not replacing the `$0` with the value but I am not sure what might be causing this error. Is that a know issue?

 
```css
#Stencil .Bd, .Bd {
    border: $0;
}

#Stencil .Bdt, #Stencil .Bdy {
    border-top: $0;
}

#Stencil .Bdb, #Stencil .Bdy {
    border-bottom: $0;
}

#Stencil .Bdc {
    border-color: $0;
}
```

**Comment by renatoi** [comment]
Which version? Make sure you are not on 3.0.0-alpha.6

**Comment by 3den** [comment]
@renatoi we are already on `3.0.0-alpha.6`, we are using `grunt-td` to run the atomizer command so i am not sure if `grunt-td` is causing the bugs or if it is a bug on atomizer it self.

**Comment by thierryk** [comment]
@3den `3.0.0-alpha.6` is the issue. Remember the hotfix from yesterday?

**Comment by 3den** [comment]
@renatoi @renatoi thanks for the quick feedback, are you guys already working on the fix? can i do something to help?

**Comment by thierryk** [comment]
`3.0.0-alpha.7` was published yesterday and it fixes the issue.

As a side note, how come we have a dupe with `Bd` (see below)? And how come that second selector does not contain the namespace?
```css
#Stencil .Bd, 
.Bd {
    border: $0;
}
```
