### ISSUE TITLE
Atomizer doesn't handle optional params well

### ISSUE THREAD

**Issue by src-code** [yahoo/atomizer#221]
Some styles have optional values, for instance `border-spacing` can have one or two values:

`border-spacing: 1em`
`border-spacing: inherit`
`border-spacing: 1em 33%`

Currently in Atomizer if a rule specifies two arguments, and you don't pass the 2nd argument, then the regex placeholder is passed through:

```css
.Bdsp\(1em\) {
  border-spacing: 1em $1;
}
.Bdsp\(i\) {
  border-spacing: inherit $1;
}
.Bdsp\(1em\,33\%\) {
  border-spacing: 1em 33%;
}
```

Seems that Atomizer should strip placeholders if they're not found.

@renatoi @thierryk
