### ISSUE TITLE
Make border classes more atomic-friendly

### ISSUE THREAD

**Issue by thierryk** [yahoo/atomizer#76]
We have the following helper classes:
```css
.Bd-0 {
    border: 0;
}
.Bd-1,
.Bdx-1,
.Bdy-1,
.Bdt-1,
.Bdend-1,
.Bdb-1,
.Bdstart-1 {
    border-width: 0;
    border-style: solid;
}
.Bdstart-1 {
    border-left-width: 1px;
}
.Bdend-1 {
    border-right-width: 1px;
}
.Bdx-1 {
    border-right-width: 1px;
    border-left-width: 1px;
}
.Bdy-1 {
    border-top-width: 1px;
    border-bottom-width: 1px;
}
```

But I think we should move all this to `rules.js` &mdash; using classes like `Bdw-`, `Bds-`, `Bdc-`.
That way users can create border styling without having to create custom Atomic classes.

Thoughts?
