### ISSUE TITLE
Plug oldIE hacks wherever needed

### ISSUE THREAD

**Issue by thierryk** [yahoo/atomizer#80]
We should plug IE hacks along with `Ov-h` and `D-ib`:

```css
.D-ib {
    display: inline-block;
    *display: inline;
    zoom: 1;
}
.Ov-h {
    overflow: hidden;
    zoom: 1;
}
```

I've removed the `Bfc` helper classes as it will be meaningless to most users and also because it maps to `overflow:hidden`, so I think it's better people know what they are dealing with.
