### ISSUE TITLE
Create a smart `LineClamp`

### ISSUE THREAD

**Issue by thierryk** [yahoo/atomizer#82]
"Line clamping" is not a simple thing as it relies on a few things:

`.LineClamp` needs:

   * `display: -webkit-box;`
   * `-webkit-box-orient: vertical;`
   * `overflow: hidden;`

while `a.LineClamp` relies on those:

   * `display: inline-block;`
   * `*display: inline;`
   * `zoom: 1;`

and `a.LineClamp:after` on these (WebKit bug):

   * `content: ".";`
   * `font-size: 0;`
   * `visibility: hidden;`
   * `display: inline-block;`
   * `overflow: hidden;`
   * `height: 0;`
   * `width: 0;`
 
The above are the styles we need regardless of the number of lines to show, because for that we need a couple more declarations:

   * `-webkit-line-clamp: <number of lines>;`
   * `max-height: <line-height * font-size>;`

Not sure what is the best way to approach this. I'm thinking of a helper and a modifier would be the easiest way to go here.
And we'd pass both the number of lines and the `max-height` we want in the suffix?
Something like this may be:

```html
<div class="LineClamp-372px">No more than 3 lines please (font-size is 16px and line-height is 1.5 in here)...</div>
```

The *first digit* is the number of lines we want followed by the `height` we need. This is a helper class, so I think we don't really have to stick to any particular syntax as long as it makes sense somehow without complicating things much.

Then helpers.css contains:

```css
[class*=LineClamp] {
   display: -webkit-box;
   -webkit-box-orient: vertical;
   overflow: hidden;
}
a[class*=LineClamp] {
   display: inline-block;
   *display: inline;
   zoom: 1;
}
a[class*=LineClamp]:after {
   content: ".";
   font-size: 0;
   visibility: hidden;
   display: inline-block;
   overflow: hidden;
   height: 0;
   width: 0;
}
```

And Atomizer outputs this:

```css
.LineClamp-372px {
   -webkit-line-clamp: 3;
   max-height: 72px; /* 16px * 1.5 * 3 */
}
```

Thoughts?

**Note** that I'd prefer to use `[class|=LineClamp]` instead of `[class*=LineClamp]` for this, but I think IE8 does not support the former :-(

**Comment by src-code** [comment]
So if I had a class `LineClamp-1150px`, how would you parse it?  Seems like we need an more explicit separator between the two values.

**Comment by thierryk** [comment]
As discussed previously, the first digit in the suffix is the `line-clamp` value, whatever follows is the `max-height` value:

```css
.LineClamp-1250px {
   -webkit-line-clamp: 1;
   max-height: 250px;
}
```

Yes, this suggests that authors won't be able to use a greater value than `9` for `line-clamp` but I don't think there are real-life examples of clamping content to 10 lines and up. Yes, separating the 2 values would allow to use any values we want, but I'm not sure what separators we should include here so may be not worth adding complexity to cater for something that may never ever be needed.
