### ISSUE TITLE
How do we deal with transform and the like?

### ISSUE THREAD

**Issue by thierryk** [yahoo/atomizer#83]
For example:

```css
transform: none
transform: matrix(1.0, 2.0, 3.0, 4.0, 5.0, 6.0)
transform: translate(12px, 50%)
transform: translateX(2em)
transform: translateY(3in)
transform: scale(2, 0.5)
transform: scaleX(2)
transform: scaleY(0.5)
transform: rotate(0.5turn)
transform: skewX(30deg)
transform: skewY(1.07rad)
transform: matrix3d(1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0)
transform: translate3d(12px, 50%, 3em)
transform: translateZ(2px)
transform: scale3d(2.5, 1.2, 0.3)
transform: scaleZ(0.3)
transform: rotate3d(1, 2.0, 3.0, 10deg)
transform: rotateX(10deg)
transform: rotateY(10deg)
transform: rotateZ(10deg)
transform: perspective(17px)

transform: translateX(10px) rotate(10deg) translateY(5px)
```

Plus:

```css
transform-function
transform-origin
transform-style
```

Following Emmet syntax things should look like this:

```css
Trfskx-30deg {
    transform: rotate(30deg);
}
.Trfsky-0.5 {
    transform: scaleY(0.5);
}
```

We could also discuss the value of going a slightly different route, using the value as a prefix and the parameter as suffix(?) It may be easier for people to make sense of the class names. For example:

```css
.SkewX-30deg {
    transform: skewX(30deg)
}
.ScaleY-0.5 {
    transform: scaleY(0.5);
}
```

A depart from what we do, but may be worth making an exception as in my opinion, it makes things much more readable.

In any case, we need to change things a little bit because we cannot plug suffix as parameters yet.

Thoughts?

**Comment by src-code** [comment]
I kind of like the idea of using the value for a prefix, it's certainly much cleaner and easier to work with, though not as consistent.

**Comment by renatoi** [comment]
I like it as well, I'd call these cases as `alias`, so it's a shortening for what the whole thing does.

I wonder, though, if we should go even further for all other classes:

```css
.Td-u,
.Underline {
    text-decoration: underline;
}
.Fw-b,
.Bold {
    font-weight: bold;
}
.Fs-i,
.Italic {
    font-style: italic;
}
```
