### ISSUE TITLE
Make this rule `!important`

### ISSUE THREAD

**Issue by thierryk** [yahoo/atomizer#87]
We need to be able to pass `!` in the class and have Atomizer writes the rule with `!important`, for example:

```html
<div class="Bgc-000!"></div>
```

```css
.Bgc-000\! {
    background: #000 !important;
}
```
